--allman false
--binarygrouping 4,8
--commas
--decimalgrouping 3,6
--elseposition same-line
--voidtype void
--exponentcase lowercase
--exponentgrouping disabled
--fractiongrouping disabled
--header ignore
--hexgrouping 4,8
--hexliteralcase uppercase
--ifdef indent
--indent 4
--indentcase false
--importgrouping testable-bottom
--linebreaks lf
#--maxwidth
--octalgrouping 4,8
--operatorfunc spaced
--patternlet hoist
--ranges spaced
--self remove
--semicolons inline
--stripunusedargs always
--swiftversion 5.7
--trimwhitespace always
--wraparguments preserve
--wrapcollections preserve


--enable blankLineAgerImports
--disable redundantSelf,trailingClosures
--enable isEmpty
--enable trailingClosures
--disable opaqueGenericParameters

